//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductChainManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientMaster
    {
        public int Client_Id { get; set; }
        public string Customer_Code { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Pin_Code { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Phone_No { get; set; }
        public Nullable<int> Ref_Client_Id { get; set; }
        public Nullable<int> Membership_Type { get; set; }
        public string Image_Path { get; set; }
        public string Signature_Path { get; set; }
        public Nullable<System.DateTime> DateTimeStamp { get; set; }
        public Nullable<bool> Can_Login { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Gender Gender1 { get; set; }
        public virtual Membership_Type Membership_Type1 { get; set; }
    }
}
