//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductChainManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PCMConnection : DbContext
    {
        public PCMConnection()
            : base("name=PCMConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account_Type> Account_Type { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Membership_Type> Membership_Type { get; set; }
        public virtual DbSet<Payment_Mode> Payment_Mode { get; set; }
        public virtual DbSet<ClientMaster> ClientMasters { get; set; }
    }
}
